Lambda-School-Labs/care-for-life-fe

- .github/workflows/nodejs.yml
- nativeApp/App.js
- nativeApp/__tests__/__snapshots__/random.test.js.snap
Description
Updated title
N/A
Type of change
Component change
New feature (non-breaking change which adds functionality)
Change Status
Complete, tested, ready to review and merge
How Has This Been Tested?
random.Test.js
Checklist
[ ✔️] My code follows the style guidelines of this project
[ ✔️ ] I have performed a self-review of my own code
[ ✔️] My code has been reviewed by at least one peer
I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
My changes generate no new warnings
I have added tests that prove my fix is effective or that my feature works
[ ✔️ ] New and existing unit tests pass locally with my changes
[ ✔️ ] There are no merge conflicts
> title update

- .github/workflows/build-test.yml
- nativeApp/__tests__/app.test.js
New Arithmetic Test
Confirms Test Environment Loads In Actions & Test Environment
> added Basic Arithmetic Test

- nativeApp/App.js
- nativeApp/components/Header/index.js
- nativeApp/navigation/AppNavigator.js
- nativeApp/screens/HomeScreen.js
- nativeApp/screens/SurveyCompletedScreen.js
- nativeApp/screens/SurveyHomeScreen.js
- nativeApp/screens/SurveyScreen.js
Added a Home drawer and Surveys drawer. The Home drawer just has text. The Surveys drawer has a screen stack containing a SurveyHomeScreen, SurveyScreen, and a SurveyCompletedScreen
N/A
Addition of drawers, screens, and navigation
N/A
> ADD navigation

- nativeApp/components/Card/index.js
- nativeApp/components/Header/index.js
- nativeApp/navigation/AppNavigator.js
- nativeApp/package-lock.json
- nativeApp/package.json
- nativeApp/screens/HomeScreen.js
- nativeApp/screens/Survey.js
- nativeApp/screens/SurveyCompletedScreen.js
- nativeApp/screens/SurveyHomeScreen.js
- nativeApp/screens/SurveyScreen.js
- nativeApp/surveys/familySurvey.js
Adds react-native-simple-survey npm package and a sample survey. 
Completion of a survey stores the results in SurveyHomeScreen.js component state
N/A
Add
N/A
> Add sample survey

- nativeApp/screens/SurveyScreen.js
Turned Off Progress Bar
Progress Bar Breaking Survey
N/A
> Turned Off Progress Bar

- nativeApp/screens/SurveyScreen.js
Survey Progress Bar Feature Debugged and Working Correctly
Progress bar no incrementing/decrementing properly
N/A
- [] My code follows the style guidelines of this project
> Survey Progress Bar Feature 

- nativeApp/screens/AllFamiliesScreen.js
- nativeApp/screens/FamilyMembersScreen.js
Adds a modal to add a family and family members
n/a
Addition
N/A
> Style modal

- nativeApp/components/UploadData/index.js
- nativeApp/screens/FamilyScreen.js
> Added basic styling to FamilyScreen buttons

- nativeApp/screens/SurveyScreen.js
> Survey Screen Styling

- nativeApp/App.js
- nativeApp/components/UploadData/index.js
- package-lock.json
> Added mutations to uploadData component

- nativeApp/screens/SurveyScreen.js
- nativeApp/surveys/annualSurvey.js
Fixes Progress Bar Bug
Adds new questions to Annual Survey
Works locally only. Not test cases
> Survey screen update

- nativeApp/config/offix.js
- nativeApp/package-lock.json
- nativeApp/package.json
> Added cross-fetch package to polyfill the browser's native fetch API

- nativeApp/App.js
- nativeApp/components/UploadData/index.js
- nativeApp/config/offix.js
- nativeApp/package-lock.json
- nativeApp/package.json
- nativeApp/queries.js
- nativeApp/screens/AllFamiliesScreen.js
> Updated npm package for AsyncStorage access

- nativeApp/config/offix.js
- nativeApp/screens/AllFamiliesScreen.js
> Apollo client setup

- nativeApp/Queries/queries.js
- nativeApp/config/offix.js
- nativeApp/package-lock.json
- nativeApp/package.json
- nativeApp/screens/LoginScreen.js
- nativeApp/screens/RegisterScreen.js
- Created mutations for login and registration of users.
- Integrated them into the Login and Register screens via the Offix useOfflineMutation hook.
- Edited each screen's handleSubmit function to await said mutation, then store the user's JWT token (provided by the mutation response) in AsyncStorage.
- Updated the Offix config to check for a valid token in AsyncStorage before attempting to send mutations to the backend GraphQL endpoint.
> Created user auth mutations and setup login/reg screens

- nativeApp/App.js
- nativeApp/config/offix.js
- nativeApp/package-lock.json
- nativeApp/package.json
- nativeApp/screens/FamilyScreen.js
- nativeApp/screens/SurveyScreen.js
- nativeApp/surveys/annualSurvey.js
Survey Screen and Family Screen Styling
No Testing
> Button height

- nativeApp/components/SurveyReview/index.js
- nativeApp/navigation/AppNavigator.js
- nativeApp/screens/SurveyCompletedScreen.js
- nativeApp/surveys/annualSurvey.js
Add style to survey review
N/A
Styling
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts
> Style survey completed screen

- nativeApp/screens/SurveyCompletedScreen.js
Added a second handleSubmit to the SurveyCompletedScreen, and set it up to queue a second offline mutation.
> Added second handleSubmit and offline mutation to SurveyCompletedScreen

- nativeApp/components/SurveyReview/index.js
- nativeApp/screens/FamilyMembersScreen.js
- nativeApp/screens/SurveyCompletedScreen.js
Adds edit functionality to SurveyCompletedScreen so answers can be changed
N/A
Additional functionality
> Edit survey modal

- nativeApp/App.js
- nativeApp/navigation/AppNavigator.js
- nativeApp/screens/AllFamiliesScreen.js
- nativeApp/screens/LoginScreen.js
Cleaned Up Login Flow
Removed unnecessary UseEffeccts
Migrated Logout logic to live in single component along with Login logic
N/A
> Cleaner Login Flow + Moved Logout Logic

- nativeApp/config/offix.js
- nativeApp/screens/LoginScreen.js
- nativeApp/screens/SurveyCompletedScreen.js
- nativeApp/surveys/annualSurvey.js
> Authentication

- nativeApp/App.js
- nativeApp/Queries/queries.js
- nativeApp/config/offix.js
- nativeApp/screens/FamilyMembersScreen.js
- nativeApp/screens/FamilyScreen.js
- nativeApp/screens/SurveyCompletedScreen.js
- nativeApp/screens/SurveyScreen.js
Added two separate offline mutations which are queued via two separate handleSubmits functions. Mutations are tested and working in Playground.
> New offline mutations to match the updated backend schema

- nativeApp/App.js
- nativeApp/api/oktaConfig.js
- nativeApp/components/SurveyReview/index.js
- nativeApp/config/offix.js
- nativeApp/navigation/AppNavigator.js
- nativeApp/package-lock.json
- nativeApp/screens/AllFamiliesScreen.js
- nativeApp/screens/FamilyMembersScreen.js
- nativeApp/screens/FamilyScreen.js
- nativeApp/screens/LoginScreen.js
- nativeApp/screens/SpashScreen.js
- nativeApp/screens/SurveyCompletedScreen.js
- nativeApp/surveys/personSurvey.js
Debugged token issue, fixed splash screen
> Debugged token issue, fixed splash screen

- README.md
- nativeApp/Queries/queries.js
I've removed the unused signUpMutation from queries.js since we are now using Okta for authentication and do not need to pass said mutation to our GraphQL endpoint.
I've also updated the Contributors badge in our documentation since the previous version was displaying incorrect data.
> Removed unused SignUpMutation and updated Readme

- README.md
Updated badges and intro in Readme docs
> Updated badges and intro in Readme docs

- package-lock.json
- src/actions/userActions.js
- src/forms/Register2.js
- src/forms/RegisterForm.js
- src/reducers/userReducer.js
- src/screens/Home.js
- src/screens/Login.js
user info saved to redux on login and register
> Redux userinfo

- src/actions/surveyActions.js
- src/routes/index.js
- src/screens/FamilyMembers.js
- src/screens/FamilySurvey.js
- src/screens/survey.js
> worker role functionality

- App.test.js
- jest/jest.setup.js
- package.json
Tweaked the test configuration to eliminate the errors. Still one warning, but that can be ignored.
> Bernies fixes
